worker:
  replicaCount: 1

global:
  conf:
    app:
      django_settings_module: config.settings
      superuser:
        username: "admin"
        email: "admin@example.com"
      media_dir: "/data/media"
    ingress:
      enabled: true
      host: papermerge.minikube
    db:
      type: "postgres"
      user: "postgres"
      name: "postgres"
    es:
      enabled: false
  secrets:
    db:
      password: ''
    app:
      secret_key: ''
      superuser:
        password: ''