apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  PAPERMERGE_MAIN_SECRET_KEY: {{ .Values.global.secrets.app.secret_key | b64enc | quote }}
  PAPERMERGE_DATABASE_PASSWORD: {{ .Values.global.secrets.db.password | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.global.secrets.app.superuser.password | b64enc | quote }}
