## Source: https://github.com/marketplace/actions/push-a-directory-to-another-repository

name: Push File

on:
  push:
    branches:
      - 'test'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes source files
      uses: gh4-io/copy-helm@v0.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './'
        destination_repo: 'gh4-io/charts'
        destination_branch: 'master'
        destination_folder: 'charts/papermerge'
        user_email: 'jason@gh4.io'
        user_name: '$GITHUB_ACTOR@users.noreply.github.com'
        commit_msg: 'Push post update'
        clean_files: '.git,.git*,.vscode,*.tgz,.values*'
        debug: false
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: gh4-io/checkout@main
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          echo "$GITHUB_ACTOR"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: '.'
